Release v1.0.0
projectsyn/component-topolvm pull request #1
Opened 2021-08-12 05:59 UTC by DebakelOrakel

Initial release of component

2021-08-12 09:24 UTC, simu requested changes
LGTM overall, some comments re. parameters with list values which should be avoided if possible.

Also the parameter documentation needs some more love

2021-08-12 09:24 UTC, simu commented on docs/modules/ROOT/pages/index.adoc
> +Topolvm (lvmd) checks a node ~10 minutes, so to extend the capacity of a node just extend its volumegroup.
```suggestion
TopoLVM (lvmd) scans all nodes every 10 minutes, so to extend the capacity of a node just extend its volumegroup and wait until the capacity change is picked up by TopoLVM.
```

2021-08-12 09:24 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Currently only one deviceclass is supported.
If only one device class is supported, why is this parameter a list?

2021-08-12 09:24 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Currently only one storageclass is supported.
If only one storageclass is supported, why is this parameter a list?

2021-08-12 09:24 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +----
The parameters documentation should explain what I can configure, and not just repeat the values I can see in `class/defaults.yml`.

Apart from the default values, I'd expect some text here which explains what the values for `name`, `volumegroup` and `sparegb` are used for by the component/TopoLVM.

2021-08-12 09:24 UTC, simu commented on docs/modules/ROOT/pages/references/parameters.adoc
> +----
Same as for storagedevices

2021-08-12 09:24 UTC, simu commented on class/defaults.yml
> +        sparegb: 1
Lists are generally undesirable (especially when we don't have to pass them to Helm as a list).

As discussed in https://github.com/appuio/component-openshift4-logging/pull/14 I would structure this as

```suggestion
    deviceclasses:
      ssd:
        volumegroup: vgssd
        sparegb: 1
        default: true
```

2021-08-12 09:24 UTC, simu commented on class/defaults.yml
> +        volumeexpansion: true
Same here (default storage class managed by component `storageclass`)

```suggestion
    storageclasses:
      ssd-local:
        fstype: xfs
        device_class: ssd
        allowVolumeExpansion: true
```

2021-08-12 09:24 UTC, simu commented on class/defaults.yml
> +              "topolvm.cybozu.com/device-class": ${topolvm:deviceclasses:0:name}
You'll have to manage the storageclass object yourself with the proposed change of format for deviceclasses and storageclasses.

2021-08-12 09:24 UTC, simu commented on component/main.jsonnet
> +};
Use the new parameter format and use `std.manifestYamlDoc` instead of string interpolation to generate the lvmd config:

```suggestion
local lvmd_config = {
  'socket-name': '/run/topolvm/lvmd.sock',
  'device-classes': [
    params.deviceclasses[name] + { name: name }
    for name in std.objectFields(params.deviceclasses)
  ]
};
local lvmd_configmap = kube.ConfigMap('topolvm-lvmd0') {
  metadata+: {
    labels+: {
      idx: '0',
      'app.kubernetes.io/name': 'topolvm',
      'app.kubernetes.io/instance': 'topolvm',
      'app.kubernetes.io/version': '0.8.3',
    },
  },
  data: {
    'lvmd.yaml': std.manifestYamlDoc(lvmd_config),
  },
};
```

2021-08-12 09:24 UTC, simu commented on component/main.jsonnet
> +
Here you'll have to also generate the storage classes with something like (not sure I managed to copy all relevant bits from the StorageClass definition in the Helm chart):

```suggestion

// Uses component `storageclass`, default class annotation is handled by the component lib of `storageclass`.
local sc = import 'lib/storageclass.libsonnet';
local make_sc_config(sc_params) =
  com.makeMergeable({
    allowVolumeExpansion: params.allowVolumeExpansion,
    parameters: {
      'csi.storage.k8s.io/fstype': params.fstype,
      'topolvm.cybozu.com/device-class': params.device_class
    }
  });
local storageclasses = [
  sc.StorageClass(name) {
    provisioner: 'topolvm.cybozu.com',
    volumeBindingMode: 'WaitForFirstConsumer',
  } + make_sc_config(params.storageclasses[name]
  for name std.objectFields(params.storageclasses)
];
```

2021-08-12 09:24 UTC, simu commented on component/main.jsonnet
> +  '21_priority_class': PriorityClass(),
```suggestion
  '21_priority_class': PriorityClass(),
  '30_storage_classes': storageclasses,
```

2021-08-12 09:24 UTC, simu commented on class/defaults.yml
> +        tag: 0.8.3
Generally, we recommend providing container image repositories and tags in a top-level parameter `images`:

```
parameters:
  topolvm:
    images:
      topolvm:
        registry: quay.io
        repository: topolvm/topolvm-with-sidecar
        tag: 0.8.3
```

And using those parameters where the image is required:

```suggestion
      image:
        # image.repository -- TopoLVM image repository to use.
        repository: ${topolvm:images:topolvm:registry}/${topolvm:images:topolvm:repository}
        # image.tag -- TopoLVM image tag to use.
        tag: ${topolvm:images:topolvm:tag}
```

2021-08-12 09:24 UTC, simu commented on component/main.jsonnet
> +            image: params.helmValues.image.repository + ':' + params.helmValues.image.tag,
```suggestion
            image: params.images.topolvm.registry + "/" + params.images.topolvm.repository + ':' + params.images.topolvm.tag,
```

2021-08-12 09:24 UTC, simu commented on class/defaults.yml
> +          csiProvisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
Maybe also move the provisioner image to parameter `images`.

2021-08-12 09:31 UTC, DebakelOrakel commented on component/main.jsonnet
> +};
Fantastic, that would also allow me to easaly implement multiple device classes!

2021-08-12 12:38 UTC, DebakelOrakel commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Currently only one deviceclass is supported.
Eventually i will implement multiple deviceclasses, so i wanted the keep the upgrade path as smooth as possible.
With eventually i mean, now, as your hint with `std.manifestYamlDoc` makes it very easy.

2021-08-12 12:38 UTC, DebakelOrakel commented on docs/modules/ROOT/pages/references/parameters.adoc
> +Currently only one storageclass is supported.
As above

2021-08-12 12:58 UTC, DebakelOrakel commented
@simu I fixed all your suggestions. Also changed the default fs from xfs to ext4, just to be more alligned with rook-ceph.

2021-08-13 11:17 UTC, simu requested changes

2021-08-13 11:17 UTC, simu commented on class/defaults.yml
> +        isdefault: false
not required when using the storageclass component library. Select default class via `parameters.storageclass.defaultClass`.

2021-08-13 11:17 UTC, simu commented on component/main.jsonnet
> +local StorageClass(name='ssd-local') = kube.StorageClass(name) {
Please use the component library of component `storageclass`.

```suggestion
local sc = import 'lib/storageclass.libsonnet';
local StorageClass(name='ssd-local') = sc.StorageClass(name) {
```

2021-08-13 13:32 UTC, simu approved these changes
LGTM, probably best to disable the component tests GitHub Action (i.e. just remove it, and adjust the .sync.yml accordingly) until we've figured out how to compile components which use component libraries.
Add the following in `.sync.yml`:

```
:global:
  feature_componentCompile: false
```

2021-08-13 14:59 UTC, merged